### ISSUE TITLE
getBaseAccessTokenUrl has $params argument which is not used, but required

### ISSUE THREAD

**Issue by hhovakimyan** [stevenmaguire/oauth2-microsoft#11]
In Microsoft.php getBaseAccessTokenUrl method, has $params argument which is required, but is not used in that method at all. This method just returns $urlAccessToken property o Microsoft class.

**Comment by stevenmaguire** [comment]
That method is implementing an abstract method defined in the base class. https://github.com/thephpleague/oauth2-client/blob/master/src/Provider/AbstractProvider.php#L248

Some providers use the`$params` to argument to compose the access token url. This package does not currently require, or support, that use case.

Do you have some need or use case that requires taking the passed `$params` argument into account?
