### ISSUE TITLE
Aquire Refresh Token

### ISSUE THREAD

**Issue by raphcadiz** [stevenmaguire/oauth2-microsoft#6]
Hi, I started using the package your made, good job there. I just wanted to know how do you handle to get a refresh token.

**Comment by stevenmaguire** [comment]
According to the documentation on Microsoft's website, the refresh token may be returned at the same time as the initial access token. 

https://msdn.microsoft.com/en-us/library/hh243647.aspx

If you are in possession of a valid refresh token you can use the refresh token workflow provided by the base package to obtain a new access token: 

https://github.com/thephpleague/oauth2-client#refreshing-a-token

```php
$existingAccessToken = getAccessTokenFromYourDataStore();

if ($existingAccessToken->hasExpired()) {
    $newAccessToken = $provider->getAccessToken('refresh_token', [
        'refresh_token' => $existingAccessToken->getRefreshToken()
    ]);

    // Purge old access token and store new access token to your data store.
}
```

Please read the documentation on Microsoft's website, verify that you are receiving a refresh token, then attempt the solution provided above.

Update this issue to let me know how it goes. If it works as expected, feel free to close this issue.

**Comment by raphcadiz** [comment]
Thank you! good work
