### ISSUE TITLE
I can't authenticate when it involves microsoft azure

### ISSUE THREAD

**Issue by raphcadiz** [stevenmaguire/oauth2-microsoft#7]
`Fatal error: Uncaught exception 'League\OAuth2\Client\Provider\Exception\IdentityProviderException' with message 'Bad Request' in /Applications/MAMP/htdocs/adobesignwp/wp-content/plugins/Gravity2PDF/lib/vendor/stevenmaguire/oauth2-microsoft/src/Provider/Microsoft.php:57 Stack trace: #0 /Applications/MAMP/htdocs/adobesignwp/wp-content/plugins/Gravity2PDF/lib/vendor/league/oauth2-client/src/Provider/AbstractProvider.php(644): Stevenmaguire\OAuth2\Client\Provider\Microsoft->checkResponse(Object(GuzzleHttp\Psr7\Response), Array) #1 /Applications/MAMP/htdocs/adobesignwp/wp-content/plugins/Gravity2PDF/lib/vendor/league/oauth2-client/src/Provider/AbstractProvider.php(560): League\OAuth2\Client\Provider\AbstractProvider->getResponse(Object(GuzzleHttp\Psr7\Request)) #2 /Applications/MAMP/htdocs/adobesignwp/wp-content/plugins/Gravity2PDF/class/gravity_merge_integrations.class.php(155): League\OAuth2\Client\Provider\AbstractProvider->getAccessToken('authorization_c...', Array) #3 [internal function]: Gravity_Merge_Integrations->setO in /Applications/MAMP/htdocs/adobesignwp/wp-content/plugins/Gravity2PDF/lib/vendor/stevenmaguire/oauth2-microsoft/src/Provider/Microsoft.php on line 57`

**Comment by stevenmaguire** [comment]
This package is for Microsoft Live. Azure support is provided with a different package. 

https://github.com/thenetworg/oauth2-azure
