### ISSUE TITLE
Endpoints

### ISSUE THREAD

**Issue by dimvic** [stevenmaguire/oauth2-microsoft#8]
Firstly, thank you for publishing the work you've put into this.

I would like to use this for authorization using office365 accounts using the the endpoints 
https://login.windows.net/common/oauth2/authorize
https://login.windows.net/common/oauth2/token

I will probably just extend the `Microsoft` provider to achieve this, but I thought I'd ask if this is something you intend to support before doing so.

**Comment by stevenmaguire** [comment]
If the documentation is similar, it's easy to support in this package. I'll look into it this weekend.

**Comment by dimvic** [comment]
If I understand well from [this](https://msdn.microsoft.com/office/office365/api/use-outlook-rest-api#RegAuthConverged)

> This approach gives you a seamless app registration and user authorization experience to get the appropriate tokens to access users' mailbox data on **Office 365 and/or Outlook.com**. If you are developing an app for Outlook.com, you must use this approach.

and [this](https://msdn.microsoft.com/office/office365/howto/authenticate-office-365-apis-using-v2) it should be no different, only the endpoint URLs should need to be configurable.

**Comment by stevenmaguire** [comment]
Is your project currently attempting to use this library? If so, I wonder if you could try something out for me? Could you open up the source provider from your vendor folder and temporarily replace the two urls and attempt to complete the authorization flow? The package handles a little bit more than just the urls so I am wondering how well it responds with your new use case.

**Comment by dimvic** [comment]
I have tried that and it works, it looks like the only difference is the endpoints.
I have not progressed with the actual application to see if the other endpoints need to be changed as well, but in regards to authentication, changing the URLs alone does work.

**Comment by stevenmaguire** [comment]
Ok. Thanks for looking into that. I've cut a new release of the project, [2.1.0](https://github.com/stevenmaguire/oauth2-microsoft/releases/tag/2.1.0) that will allow you to override the default urls auth, token, and resource owner. 

```php
$provider = new Stevenmaguire\OAuth2\Client\Provider\Microsoft([
    // Required
    'clientId'                  => '{microsoft-client-id}',
    'clientSecret'              => '{microsoft-client-secret}',
    'redirectUri'               => 'https://example.com/callback-url',
    // Optional
    'urlAuthorize'              => 'https://login.windows.net/common/oauth2/authorize',
    'urlAccessToken'            => 'https://login.windows.net/common/oauth2/token',
    'urlResourceOwnerDetails'   => 'https://outlook.office.com/api/v1.0/me'
]);
```

**Comment by dimvic** [comment]
Thank you very much, it is working nicely.

I see that you also have
```php
    protected function getUserImage(array $response, AccessToken $token)
    {
        $url = 'https://apis.live.net/v5.0/'.$response['id'].'/picture';
        $request = $this->getAuthenticatedRequest('get', $url, $token);
        $response = $this->getResponse($request);
        return json_decode((string) $response->getBody(), true);
    }
```

I am not going to be using this, but maybe change `$urlResourceOwnerDetails` to `$urlResources` and use that as a prefix for all resources in case someone else needs it?

**Comment by stevenmaguire** [comment]
Good catch. I'm likely going to remove this method, as it's not specific to auth flow and once you obtain a token you can use that to request any URL you'd like.
